create binary installers from Rexfiles

diff --git a/bin/rexify b/bin/rexify
--- a/bin/rexify
+++ b/bin/rexify
@@ -144,6 +144,11 @@ if ( !$ARGV[0] || join( ",", @ARGV ) =~ m/\-h,|\-\-help,/ || $ARGV[0] eq "--help
   print STDERR "   box - Template to use for Rex::Commands::Box projects.\n";
 
   print STDERR "\n";
+  print STDERR "Application Bundle Commands:\n";
+  print STDERR "\n";
+  print STDERR "\t--bundle\tCreate an all-containing redistributable binary application.\n";
+  print STDERR "\t--task=taskname\tWhich task should be executed. default: setup\n";
+  print STDERR "\n";
   print STDERR "Rex-JobControl Commands:\n";
   print STDERR "\n";
   print STDERR "\t--upload\tUpload Rexfile to JobControl server.\n";
@@ -539,6 +544,64 @@ sub install_perl_module {
   else {
     print "[ok]\n";
   }
+}
+
+if(exists $opts->{bundle}) {
+  # bundle everything to an application
+
+  CORE::mkdir("rex.payload");
+  system "cp -vR * rex.payload/ 2>/dev/null";
+  system "rm -rf rex.payload/rex.payload";
+
+  my $rex = File::Spec->catfile(dirname($0), "rex");
+  my $tmp_args_file = File::Spec->catfile(File::Spec->tmpdir(), "pp.args.$$.tmp");
+  open(my $fh, ">", $tmp_args_file) or die($!);
+  print $fh template('@pp.args.tpl');
+  close($fh);
+
+  # build the perl and application
+  system "pp \@$tmp_args_file -o rex.payload/rex.bin $rex";
+
+  # find libssh2.so and libexpat.so
+  my $arch = qx{uname -m};
+  chomp $arch;
+
+  my $elf = "ELF32";
+  if($arch eq "x86_64") {
+    $elf = "ELF64";
+  }
+
+  CORE::mkdir(File::Spec->catdir("rex.payload", "lib.bin"));
+  my @libexpat = qx{find /usr/lib /usr/lib32 /usr/lib64 /lib -name 'libexpat.so*' -type f 2>/dev/null};
+  my @libssh2  = qx{find /usr/lib /usr/lib32 /usr/lib64 /lib -name 'libssh2.so*' -type f 2>/dev/null};
+  chomp @libexpat;
+  chomp @libssh2;
+
+  for my $f (@libexpat, @libssh2) {
+    my $elf_class = qx{readelf -h $f | grep Class:};
+    # only copy architecture specific files
+    # currently no multi arch support
+    if($elf_class =~ m/$elf/) {
+      system "cp -va $f " . File::Spec->catdir("rex.payload", "lib.bin");
+    }
+  }
+
+  system "cd rex.payload/lib.bin ; ln -s " . basename($libssh2[0]) . " libssh2.so.1";
+  system "cd rex.payload/lib.bin ; ln -s " . basename($libexpat[0]) . " libexpat.so.1";
+
+  # create wrapper script.
+  open(my $fh2, ">", "rex.sh") or die($!);
+  print $fh2 template('@bundle.sh.tpl', task => 'setup');
+  close($fh2);
+
+  system "cd rex.payload ; tar czf ../rex.payload.tar.gz *";
+  system "cat rex.sh rex.payload.tar.gz >rex.selfextract.sbx ; chmod 755 rex.selfextract.sbx";
+
+  CORE::unlink($tmp_args_file);
+  CORE::unlink("rex.sh");
+  system "rm -rf rex.payload";
+  CORE::unlink("rex.payload.tar.gz");
+  exit 0;
 }
 
 if ( exists $opts->{upload}
@@ -952,4 +1015,343 @@ License: {{ THE LICENSE }}
 Require:
    - Other::Rex::Module
    - 2nd::Rex::Module
+@end
+
+
+@pp.args.tpl
+-M Net::OpenSSH::ShellQuoter::POSIX 
+-M Net::SFTP::Foreign::Backend::Unix
+-M Sys::Syslog
+-M Net::OpenSSH
+-M Net::SFTP::Foreign
+-M UNIVERSAL
+-M Rex::Virtualization
+-M Rex::User::Linux
+-M Rex::User::FreeBSD
+-M Rex::User::SunOS
+-M Rex::User::OpenWrt
+-M Rex::User::NetBSD
+-M Rex::User::OpenBSD
+-M Rex::Virtualization::VBox::delete
+-M Rex::Virtualization::VBox::list
+-M Rex::Virtualization::VBox::info
+-M Rex::Virtualization::VBox::shutdown
+-M Rex::Virtualization::VBox::reboot
+-M Rex::Virtualization::VBox::status
+-M Rex::Virtualization::VBox::import
+-M Rex::Virtualization::VBox::forward_port
+-M Rex::Virtualization::VBox::create
+-M Rex::Virtualization::VBox::bridge
+-M Rex::Virtualization::VBox::option
+-M Rex::Virtualization::VBox::start
+-M Rex::Virtualization::VBox::share_folder
+-M Rex::Virtualization::VBox::destroy
+-M Rex::Virtualization::VBox::guestinfo
+-M Rex::Virtualization::VBox
+-M Rex::Virtualization::LibVirt
+-M Rex::Virtualization::Docker
+-M Rex::Virtualization::LibVirt::delete
+-M Rex::Virtualization::LibVirt::blklist
+-M Rex::Virtualization::LibVirt::list
+-M Rex::Virtualization::LibVirt::info
+-M Rex::Virtualization::LibVirt::shutdown
+-M Rex::Virtualization::LibVirt::reboot
+-M Rex::Virtualization::LibVirt::dumpxml
+-M Rex::Virtualization::LibVirt::status
+-M Rex::Virtualization::LibVirt::import
+-M Rex::Virtualization::LibVirt::create
+-M Rex::Virtualization::LibVirt::option
+-M Rex::Virtualization::LibVirt::start
+-M Rex::Virtualization::LibVirt::vncdisplay
+-M Rex::Virtualization::LibVirt::clone
+-M Rex::Virtualization::LibVirt::iflist
+-M Rex::Virtualization::LibVirt::destroy
+-M Rex::Virtualization::LibVirt::hypervisor
+-M Rex::Virtualization::LibVirt::guestinfo
+-M Rex::Virtualization::Base
+-M Rex::Virtualization::Docker::delete
+-M Rex::Virtualization::Docker::list
+-M Rex::Virtualization::Docker::daemon
+-M Rex::Virtualization::Docker::info
+-M Rex::Virtualization::Docker::shutdown
+-M Rex::Virtualization::Docker::reboot
+-M Rex::Virtualization::Docker::create
+-M Rex::Virtualization::Docker::start
+-M Rex::Virtualization::Docker::destroy
+-M Rex::Shared::Var::Scalar
+-M Rex::Shared::Var::Array
+-M Rex::Shared::Var::Hash
+-M Rex::Shared::Var
+-M Rex::Hardware
+-M Rex::Args::Single
+-M Rex::Args::Integer
+-M Rex::Args::String
+-M Rex::Inventory::DMIDecode
+-M Rex::Inventory::Proc::Cpuinfo
+-M Rex::Inventory::SMBios::SystemInformation
+-M Rex::Inventory::SMBios::CPU
+-M Rex::Inventory::SMBios::Memory
+-M Rex::Inventory::SMBios::BaseBoard
+-M Rex::Inventory::SMBios::Section
+-M Rex::Inventory::SMBios::MemoryArray
+-M Rex::Inventory::SMBios::Bios
+-M Rex::Inventory::Hal
+-M Rex::Inventory::SMBios
+-M Rex::Inventory::Bios
+-M Rex::Inventory::HP::ACU
+-M Rex::Inventory::Hal::Object::Net
+-M Rex::Inventory::Hal::Object::Storage
+-M Rex::Inventory::Hal::Object::Volume
+-M Rex::Inventory::Hal::Object
+-M Rex::Inventory::DMIDecode::SystemInformation
+-M Rex::Inventory::DMIDecode::CPU
+-M Rex::Inventory::DMIDecode::Memory
+-M Rex::Inventory::DMIDecode::BaseBoard
+-M Rex::Inventory::DMIDecode::Section
+-M Rex::Inventory::DMIDecode::MemoryArray
+-M Rex::Inventory::DMIDecode::Bios
+-M Rex::Inventory::Proc
+-M Rex::File::Parser::Data
+-M Rex::File::Parser::Ini
+-M Rex::Notify
+-M Rex::Logger
+-M Rex::Commands
+-M Rex::Hook
+-M Rex::Exporter
+-M Rex::Box::VBox
+-M Rex::Box::Amazon
+-M Rex::Box::Base
+-M Rex::Box::KVM
+-M Rex::Output::JUnit
+-M Rex::Output::Base
+-M Rex::Report::YAML
+-M Rex::Report::Base
+-M Rex::Inventory
+-M Rex::FS::File
+-M Rex::Output
+-M Rex::Cron
+-M Rex::Batch
+-M Rex::CMDB
+-M Rex::TaskList
+-M Rex::Pkg::SuSE
+-M Rex::Pkg::Debian
+-M Rex::Pkg::Ubuntu
+-M Rex::Pkg::Gentoo
+-M Rex::Pkg::FreeBSD
+-M Rex::Pkg::SunOS
+-M Rex::Pkg::OpenWrt
+-M Rex::Pkg::Redhat
+-M Rex::Pkg::NetBSD
+-M Rex::Pkg::Base
+-M Rex::Pkg::ALT
+-M Rex::Pkg::Mageia
+-M Rex::Pkg::OpenBSD
+-M Rex::Pkg::SunOS::pkg
+-M Rex::Pkg::SunOS::OpenCSW
+-M Rex::Template
+-M Rex::Profiler
+-M Rex::User
+-M Rex::Box
+-M Rex::Resource::Common
+-M Rex::Cloud
+-M Rex::SCM::Subversion
+-M Rex::SCM::Git
+-M Rex::Report
+-M Rex::Value
+-M Rex::Group
+-M Rex::CMDB::YAML
+-M Rex::CMDB::Base
+-M Rex::Group::Entry::Server
+-M Rex::Group::Lookup::Command
+-M Rex::Group::Lookup::File
+-M Rex::Group::Lookup::DBI
+-M Rex::Group::Lookup::YAML
+-M Rex::Group::Lookup::XML
+-M Rex::Group::Lookup::INI
+-M Rex::Task
+-M Rex::Resource
+-M Rex::Interface::Fs::Sudo
+-M Rex::Interface::Fs::HTTP
+-M Rex::Interface::Fs::Local
+-M Rex::Interface::Fs::Base
+-M Rex::Interface::Fs::SSH
+-M Rex::Interface::Fs::OpenSSH
+-M Rex::Interface::File::Sudo
+-M Rex::Interface::File::HTTP
+-M Rex::Interface::File::Local
+-M Rex::Interface::File::Base
+-M Rex::Interface::File::SSH
+-M Rex::Interface::File::OpenSSH
+-M Rex::Interface::Cache::YAML
+-M Rex::Interface::Cache::Base
+-M Rex::Interface::Connection::Fake
+-M Rex::Interface::Connection::HTTP
+-M Rex::Interface::Connection::Local
+-M Rex::Interface::Connection::HTTPS
+-M Rex::Interface::Connection::Base
+-M Rex::Interface::Connection::SSH
+-M Rex::Interface::Connection::OpenSSH
+-M Rex::Interface::File
+-M Rex::Interface::Connection
+-M Rex::Interface::Executor
+-M Rex::Interface::Shell
+-M Rex::Interface::Exec::Sudo
+-M Rex::Interface::Exec::HTTP
+-M Rex::Interface::Exec::Local
+-M Rex::Interface::Exec::Base
+-M Rex::Interface::Exec::SSH
+-M Rex::Interface::Exec::OpenSSH
+-M Rex::Interface::Executor::Default
+-M Rex::Interface::Executor::Base
+-M Rex::Interface::Exec
+-M Rex::Interface::Fs
+-M Rex::Interface::Shell::Ksh
+-M Rex::Interface::Shell::Zsh
+-M Rex::Interface::Shell::Ash
+-M Rex::Interface::Shell::Default
+-M Rex::Interface::Shell::Sh
+-M Rex::Interface::Shell::Bash
+-M Rex::Interface::Shell::Tcsh
+-M Rex::Interface::Shell::Base
+-M Rex::Interface::Shell::Csh
+-M Rex::Interface::Cache
+-M Rex::Fork::Task
+-M Rex::Fork::Manager
+-M Rex::CLI
+-M Rex::Test::Base
+-M Rex::Test::Base::has_content
+-M Rex::Test::Base::has_file
+-M Rex::Test::Base::has_package
+-M Rex::Test::Base::has_service_stopped
+-M Rex::Test::Base::has_service_running
+-M Rex::Constants
+-M Rex::Hardware::Memory
+-M Rex::Hardware::Network
+-M Rex::Hardware::VirtInfo
+-M Rex::Hardware::Swap
+-M Rex::Hardware::Kernel
+-M Rex::Hardware::Host
+-M Rex::Hardware::Network::Linux
+-M Rex::Hardware::Network::FreeBSD
+-M Rex::Hardware::Network::Solaris
+-M Rex::Hardware::Network::NetBSD
+-M Rex::Hardware::Network::OpenBSD
+-M Rex::Hardware::Network::Darwin
+-M Rex::Cloud::Amazon
+-M Rex::Cloud::Base
+-M Rex::Cloud::Jiffybox
+-M Rex::Cloud::OpenStack
+-M Rex::Transaction
+-M Rex::Commands::LVM
+-M Rex::Commands::Virtualization
+-M Rex::Commands::Sysctl
+-M Rex::Commands::SimpleCheck
+-M Rex::Commands::Rsync
+-M Rex::Commands::Notify
+-M Rex::Commands::Tail
+-M Rex::Commands::Inventory
+-M Rex::Commands::Cron
+-M Rex::Commands::DB
+-M Rex::Commands::File
+-M Rex::Commands::Gather
+-M Rex::Commands::Network
+-M Rex::Commands::User
+-M Rex::Commands::Box
+-M Rex::Commands::Upload
+-M Rex::Commands::JobControl
+-M Rex::Commands::Cloud
+-M Rex::Commands::Run
+-M Rex::Commands::Download
+-M Rex::Commands::Process
+-M Rex::Commands::Sync
+-M Rex::Commands::Kernel
+-M Rex::Commands::MD5
+-M Rex::Commands::Iptables
+-M Rex::Commands::Partition
+-M Rex::Commands::Service
+-M Rex::Commands::Pkg
+-M Rex::Commands::Fs
+-M Rex::Commands::Host
+-M Rex::Commands::SCM
+-M Rex::Service
+-M Rex::Pkg
+-M Rex::Cron::Linux
+-M Rex::Cron::SunOS
+-M Rex::Cron::Base
+-M Rex::Config
+-M Rex::Helper::System
+-M Rex::Helper::Run
+-M Rex::Helper::SSH2
+-M Rex::Helper::DBI
+-M Rex::Helper::Encode
+-M Rex::Helper::Array
+-M Rex::Helper::INI
+-M Rex::Helper::Misc
+-M Rex::Helper::SSH2::Expect
+-M Rex::Helper::UserAgent
+-M Rex::Helper::Hash
+-M Rex::Helper::URI
+-M Rex::Helper::Path
+-M Rex::TaskList::Parallel_ForkManager
+-M Rex::TaskList::Base
+-M Rex::Require
+-M Rex::Args
+-M Rex::Sudo::File
+-M Rex::Test
+-M Rex::Service::SuSE
+-M Rex::Service::Debian
+-M Rex::Service::ALT::systemd
+-M Rex::Service::Gentoo::systemd
+-M Rex::Service::Mageia::systemd
+-M Rex::Service::Ubuntu
+-M Rex::Service::Gentoo
+-M Rex::Service::FreeBSD
+-M Rex::Service::SunOS
+-M Rex::Service::Redhat::systemd
+-M Rex::Service::OpenWrt
+-M Rex::Service::Redhat
+-M Rex::Service::NetBSD
+-M Rex::Service::Base
+-M Rex::Service::ALT
+-M Rex::Service::Mageia
+-M Rex::Service::OpenBSD
+-M Rex::Service::SunOS::svcadm
+-M Rex::Service::SuSE::systemd
+-M Rex
+-M Net::SSH2
+@end
+
+@bundle.sh.tpl
+#!/bin/bash
+echo ""
+echo "Self Extracting Rex Installer"
+echo ""
+
+export TMPDIR=`mktemp -d /tmp/rex.bundle.XXXXXX`
+
+ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`
+
+echo -n "Extracting archive...  "
+echo
+
+tail -n+$ARCHIVE $0 | tar xz -C $TMPDIR
+
+if [ "$?" != "0" ]; then
+  echo "failed."
+  exit 1
+fi
+
+echo "done."
+
+CDIR=`pwd`
+cd $TMPDIR
+export LD_LIBRARY_PATH=`pwd`/lib.bin:$LD_LIBRARY_PATH
+./rex.bin -f `pwd`/Rexfile $*
+
+cd $CDIR
+rm -rf $TMPDIR
+
+exit 0
+
+__ARCHIVE_BELOW__
 @end
